FROM apache/airflow:2.10.3

USER root

RUN apt-get update &&     apt-get install -y --no-install-recommends openjdk-17-jdk-headless &&     apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir     apache-airflow-providers-apache-spark==4.10.0     apache-airflow-providers-amazon==8.28.0     boto3==1.35.0
