services:
  dremio:
    image: dremio/dremio-oss:latest
    platform: linux/x86_64
    container_name: dremio_fhbd_1
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - semana5-proyecto-parcial_data-stack

networks:
  semana5-proyecto-parcial_data-stack:
    external: true
