services:
  trino:
    image: trinodb/trino:latest
    container_name: trino_fhbd_1
    ports:
      - "8080:8080"
    networks:
      - semana5-proyecto-parcial_data-stack
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/config:/etc/trino/config
      - ./trino/auth:/etc/trino/auth
    environment:
      # 👇 definimos credenciales aquí y las inyectamos en los archivos
      TRINO_USER: admin
      TRINO_PASSWORD: password

networks:
  semana5-proyecto-parcial_data-stack:
    external: true
